name: Bug report
description: Report a reproducible bug
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: repro
    attributes:
      label: Repro steps
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / output
